name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.68.3
        TARGET_REPO: nicocasaisd/nicocasaisd.github.io
        TARGET_BRANCH: main
        TOKEN: ${{ secrets.TOKEN }}
        CNAME: nicocasaisd.github.io
